const styles = {
  page: {
    minHeight: '100vh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: '#0d0f14',
    fontFamily: 'system-ui, sans-serif',
  },
  card: {
    width: 400,
    background: '#161a22',
    borderRadius: 20,
    padding: 20,
    boxShadow: '0 10px 40px rgba(0,0,0,0.4)',
    color: '#f2f2f2',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  title: { fontSize: 20, fontWeight: 600, margin: 0 },
  walletBtn: {
    background: '#232838',
    color: '#f2f2f2',
    border: 'none',
    borderRadius: 12,
    padding: '8px 14px',
    fontSize: 13,
    cursor: 'pointer',
  },
  tokenBox: {
    background: '#1d222c',
    borderRadius: 16,
    padding: 14,
    marginBottom: 4,
  },
  tokenBoxHeader: { fontSize: 12, color: '#8a90a2', marginBottom: 6 },
  tokenRow: { display: 'flex', alignItems: 'center', gap: 10 },
  amountInput: {
    flex: 1,
    background: 'transparent',
    border: 'none',
    outline: 'none',
    color: '#f2f2f2',
    fontSize: 24,
    minWidth: 0,
  },
  tokenSelect: {
    background: '#2a3040',
    color: '#f2f2f2',
    border: 'none',
    borderRadius: 10,
    padding: '8px 10px',
    fontSize: 14,
    cursor: 'pointer',
  },
  flipRow: { display: 'flex', justifyContent: 'center', margin: '-4px 0' },
  flipBtn: {
    background: '#232838',
    border: '4px solid #161a22',
    borderRadius: 10,
    color: '#f2f2f2',
    width: 32,
    height: 32,
    cursor: 'pointer',
    zIndex: 1,
  },
  hint: { fontSize: 12, color: '#8a90a2', marginTop: 6 },
  actionBtn: {
    width: '100%',
    marginTop: 14,
    padding: '14px',
    borderRadius: 14,
    border: 'none',
    background: '#5b6cff',
    color: '#fff',
    fontSize: 16,
    fontWeight: 600,
    cursor: 'pointer',
  },
  successMsg: {
    marginTop: 12,
    fontSize: 13,
    color: '#7ee787',
    textAlign: 'center',
  },
  warning: {
    marginTop: 14,
    fontSize: 11,
    color: '#e3a13f',
    background: '#2a2418',
    borderRadius: 10,
    padding: 10,
    lineHeight: 1.4,
  },
}

export default styles